### PR TITLE
[Fix] Remapping on VLP-32C driver

### PR DESCRIPTION
**Pull request by aohsato**
## Status
**DEVELOPMENT**

## Description
I fixed remapping from `velodyne_points` to `points_raw` on VLP-32C driver.

## Todos
- [ ] Tests

### CODE REVIEW

**Comment by amc-nu** [comment]
@aohsato can you please check  and fix CI error?
thanks!

**Comment by aohsato** [comment]
@amc-nu Mainly, some `hztest` failed. You already passed these test in current `Autoware` branch, right?
https://travis-ci.org/CPFL/velodyne/jobs/448883411#L3512

```
[ROSTEST]-----------------------------------------------------------------------
[velodyne_pointcloud.rosunit-multi_nodelet_32e_test/test_hz][FAILURE]-----------
no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
[velodyne_pointcloud.rosunit-multi_nodelet_vlp16_test/test_hz][FAILURE]---------
no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 2
 * ERRORS: 0
 * FAILURES: 2
```

**Comment by amc-nu** [comment]
yes, it is passing.
https://travis-ci.org/CPFL/velodyne/builds/447646358

**Comment by aohsato** [comment]
@amc-nu Hmm, I don't understand why not passing... Okey I'll check.

**Review by amc-nu — APPROVED** [review]

**Pull request merged**
